# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$('#testBtn').click ->
  cnt = 4
  btn = $(this)
  btn.button 'loading'
  setTimeout (->
    cnt++
    btn.button 'reset'
    btn.text '  ' + cnt
    return
  ), 1000
  return
$('#testBtnDown').click ->
  cnt = 4
  btn = $(this)
  btn.button 'loading'
  setTimeout (->
    if cnt > 0
      cnt--
    btn.button 'reset'
    btn.text '  ' + cnt
    return
  ), 1000
  return

# ---
# generated by js2coffee 2.2.0